// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_instrument_play_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_instrument_play_type.proto</summary>
  public static partial class EnumEInstrumentPlayTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_instrument_play_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEInstrumentPlayTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFlbnVtX2VfaW5zdHJ1bWVudF9wbGF5X3R5cGUucHJvdG8SBnpwcm90byp0",
            "ChNFSW5zdHJ1bWVudFBsYXlUeXBlEhoKFkluc3RydW1lbnRQbGF5VHlwZU5v",
            "bmUQABIeChpJbnN0cnVtZW50UGxheVR5cGVQbGF5Tm90ZRABEiEKHUluc3Ry",
            "dW1lbnRQbGF5VHlwZVJlbGVhc2VOb3RlEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EInstrumentPlayType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EInstrumentPlayType {
    [pbr::OriginalName("InstrumentPlayTypeNone")] InstrumentPlayTypeNone = 0,
    [pbr::OriginalName("InstrumentPlayTypePlayNote")] InstrumentPlayTypePlayNote = 1,
    [pbr::OriginalName("InstrumentPlayTypeReleaseNote")] InstrumentPlayTypeReleaseNote = 2,
  }

  #endregion

}

#endregion Designer generated code
