// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_shape_shift_mask.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_shape_shift_mask.proto</summary>
  public static partial class EnumEShapeShiftMaskReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_shape_shift_mask.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEShapeShiftMaskReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1lbnVtX2Vfc2hhcGVfc2hpZnRfbWFzay5wcm90bxIGenByb3RvKoUCCg9F",
            "U2hhcGVTaGlmdE1hc2sSFgoSRVNoYXBlU2hpZnRNYXNrRGVmEAASHwobRVNo",
            "YXBlU2hpZnRDaGFuZ2VQcm9mZXNzaW9uEAESIAocRVNoYXBlU2hpZnRUYWtl",
            "b2ZmUHJvZmVzc2lvbhACEhsKF0VTaGFwZVNoaWZ0UmVwbGFjZU1vZGVsEAQS",
            "HgoaRVNoYXBlU2hpZnRVc2VNb2RlbEFuaW1UcGwQCBIdChlFU2hhcGVTaGlm",
            "dFVzZU1vZGVsV2VhcG9uEBASGQoVRVNoYXBlU2hpZnRIaWRlV2VhcG9uECAS",
            "IAocRVNoYXBlU2hpZnRSZXBsYWNlTW9kZWxMYXllchBAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EShapeShiftMask), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EShapeShiftMask {
    [pbr::OriginalName("EShapeShiftMaskDef")] Def = 0,
    [pbr::OriginalName("EShapeShiftChangeProfession")] EshapeShiftChangeProfession = 1,
    [pbr::OriginalName("EShapeShiftTakeoffProfession")] EshapeShiftTakeoffProfession = 2,
    [pbr::OriginalName("EShapeShiftReplaceModel")] EshapeShiftReplaceModel = 4,
    [pbr::OriginalName("EShapeShiftUseModelAnimTpl")] EshapeShiftUseModelAnimTpl = 8,
    [pbr::OriginalName("EShapeShiftUseModelWeapon")] EshapeShiftUseModelWeapon = 16,
    [pbr::OriginalName("EShapeShiftHideWeapon")] EshapeShiftHideWeapon = 32,
    [pbr::OriginalName("EShapeShiftReplaceModelLayer")] EshapeShiftReplaceModelLayer = 64,
  }

  #endregion

}

#endregion Designer generated code
