// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_dungeon_play_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_dungeon_play_type.proto</summary>
  public static partial class EnumEDungeonPlayTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_dungeon_play_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEDungeonPlayTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5lbnVtX2VfZHVuZ2Vvbl9wbGF5X3R5cGUucHJvdG8SBnpwcm90byrWBAoQ",
            "RUR1bmdlb25QbGF5VHlwZRIXChNEdW5nZW9uUGxheVR5cGVOdWxsEAASGQoV",
            "RHVuZ2VvblBsYXlUeXBlTm9ybWFsEAESGQoVRHVuZ2VvblBsYXlUeXBlTGlu",
            "ZWFyEAISHwobRHVuZ2VvblBsYXlUeXBlUGxhbmV0TWVtb3J5EAMSIwofRHVu",
            "Z2VvblBsYXlUeXBlUGxhbmV0TWVtb3J5TG9vcBAEEhoKFkR1bmdlb25QbGF5",
            "VHlwZVBhcmtvdXIQBRIXChNEdW5nZW9uUGxheVR5cGVGbHV4EAYSFgoSRHVu",
            "Z2VvblRodW5kZXJGbHV4EAcSHQoZRHVuZ2VvblBsYXlUeXBlSGVyb05vcm1h",
            "bBAIEiAKHER1bmdlb25QbGF5VHlwZUhlcm9DaGFsbGVuZ2UQCRIcChhEdW5n",
            "ZW9uUGxheVR5cGVDb21tdW5pdHkQChIbChdEdW5nZW9uUGxheVR5cGVIb21l",
            "bGFuZBALEh0KGUR1bmdlb25QbGF5VHlwZVVuaW9uU2NlbmUQDBIcChhEdW5n",
            "ZW9uUGxheVR5cGVVbmlvblBsYXkQDRIcChhEdW5nZW9uUGxheVR5cGVXb3Js",
            "ZEJvc3MQDxIaChZEdW5nZW9uUGxheVdlZWtseVRvd2VyEBASHQoZRHVuZ2Vv",
            "blBsYXlUeXBlTWFzdGVyTW9kZRAREhcKE0R1bmdlb25QbGF5VHlwZVJhaWQQ",
            "EhIYChREdW5nZW9uUGxheVR5cGVSb2d1ZRATEhsKF0R1bmdlb25QbGF5VHlw",
            "ZUhpZGVTZWVrEBRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EDungeonPlayType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EDungeonPlayType {
    [pbr::OriginalName("DungeonPlayTypeNull")] DungeonPlayTypeNull = 0,
    [pbr::OriginalName("DungeonPlayTypeNormal")] DungeonPlayTypeNormal = 1,
    [pbr::OriginalName("DungeonPlayTypeLinear")] DungeonPlayTypeLinear = 2,
    [pbr::OriginalName("DungeonPlayTypePlanetMemory")] DungeonPlayTypePlanetMemory = 3,
    [pbr::OriginalName("DungeonPlayTypePlanetMemoryLoop")] DungeonPlayTypePlanetMemoryLoop = 4,
    [pbr::OriginalName("DungeonPlayTypeParkour")] DungeonPlayTypeParkour = 5,
    [pbr::OriginalName("DungeonPlayTypeFlux")] DungeonPlayTypeFlux = 6,
    [pbr::OriginalName("DungeonThunderFlux")] DungeonThunderFlux = 7,
    [pbr::OriginalName("DungeonPlayTypeHeroNormal")] DungeonPlayTypeHeroNormal = 8,
    [pbr::OriginalName("DungeonPlayTypeHeroChallenge")] DungeonPlayTypeHeroChallenge = 9,
    [pbr::OriginalName("DungeonPlayTypeCommunity")] DungeonPlayTypeCommunity = 10,
    [pbr::OriginalName("DungeonPlayTypeHomeland")] DungeonPlayTypeHomeland = 11,
    [pbr::OriginalName("DungeonPlayTypeUnionScene")] DungeonPlayTypeUnionScene = 12,
    [pbr::OriginalName("DungeonPlayTypeUnionPlay")] DungeonPlayTypeUnionPlay = 13,
    [pbr::OriginalName("DungeonPlayTypeWorldBoss")] DungeonPlayTypeWorldBoss = 15,
    [pbr::OriginalName("DungeonPlayWeeklyTower")] DungeonPlayWeeklyTower = 16,
    [pbr::OriginalName("DungeonPlayTypeMasterMode")] DungeonPlayTypeMasterMode = 17,
    [pbr::OriginalName("DungeonPlayTypeRaid")] DungeonPlayTypeRaid = 18,
    [pbr::OriginalName("DungeonPlayTypeRogue")] DungeonPlayTypeRogue = 19,
    [pbr::OriginalName("DungeonPlayTypeHideSeek")] DungeonPlayTypeHideSeek = 20,
  }

  #endregion

}

#endregion Designer generated code
