// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_ichiban_event_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_ichiban_event_type.proto</summary>
  public static partial class EnumEIchibanEventTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_ichiban_event_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEIchibanEventTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9lbnVtX2VfaWNoaWJhbl9ldmVudF90eXBlLnByb3RvEgZ6cHJvdG8qsQIK",
            "EUVJY2hpYmFuRXZlbnRUeXBlEhkKFUVJY2hpYmFuRXZlbnRUeXBlTnVsbBAA",
            "EhkKFUVJY2hpYmFuRXZlbnRMdWNrRnJlZRABEhsKF0VJY2hpYmFuRXZlbnRM",
            "dWNrUmV0dXJuEAISHAoYRUljaGliYW5FdmVudEx1Y2tBZGRQcm9iEAMSHAoY",
            "RUljaGliYW5FdmVudEx1Y2tFeGNsdWRlEAQSJgohRUljaGliYW5FdmVudElu",
            "ZXZpdGFibGVSYW5kb21HaWZ0EN4HEiUKIEVJY2hpYmFuRXZlbnRJbmV2aXRh",
            "YmxlR3VhcmFudGVlEN8HEiIKHUVJY2hpYmFuRXZlbnRJbmV2aXRhYmxlUmV0",
            "dXJuEOAHEhoKFUVJY2hpYmFuRXZlbnRUeXBlTm9uZRDnB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EIchibanEventType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EIchibanEventType {
    [pbr::OriginalName("EIchibanEventTypeNull")] Null = 0,
    [pbr::OriginalName("EIchibanEventLuckFree")] EichibanEventLuckFree = 1,
    [pbr::OriginalName("EIchibanEventLuckReturn")] EichibanEventLuckReturn = 2,
    [pbr::OriginalName("EIchibanEventLuckAddProb")] EichibanEventLuckAddProb = 3,
    [pbr::OriginalName("EIchibanEventLuckExclude")] EichibanEventLuckExclude = 4,
    [pbr::OriginalName("EIchibanEventInevitableRandomGift")] EichibanEventInevitableRandomGift = 990,
    [pbr::OriginalName("EIchibanEventInevitableGuarantee")] EichibanEventInevitableGuarantee = 991,
    [pbr::OriginalName("EIchibanEventInevitableReturn")] EichibanEventInevitableReturn = 992,
    [pbr::OriginalName("EIchibanEventTypeNone")] None = 999,
  }

  #endregion

}

#endregion Designer generated code
