// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_instrument_play_range.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_instrument_play_range.proto</summary>
  public static partial class EnumEInstrumentPlayRangeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_instrument_play_range.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEInstrumentPlayRangeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJlbnVtX2VfaW5zdHJ1bWVudF9wbGF5X3JhbmdlLnByb3RvEgZ6cHJvdG8q",
            "cAoURUluc3RydW1lbnRQbGF5UmFuZ2USGwoXRUluc3RydW1lbnRQbGF5UmFu",
            "Z2VBbGwQABIdChlFSW5zdHJ1bWVudFBsYXlSYW5nZVVuaW9uEAESHAoYRUlu",
            "c3RydW1lbnRQbGF5UmFuZ2VUZWFtEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EInstrumentPlayRange), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EInstrumentPlayRange {
    [pbr::OriginalName("EInstrumentPlayRangeAll")] All = 0,
    [pbr::OriginalName("EInstrumentPlayRangeUnion")] Union = 1,
    [pbr::OriginalName("EInstrumentPlayRangeTeam")] Team = 2,
  }

  #endregion

}

#endregion Designer generated code
