// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_hide_seek_camp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_hide_seek_camp.proto</summary>
  public static partial class EnumEHideSeekCampReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_hide_seek_camp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEHideSeekCampReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtlbnVtX2VfaGlkZV9zZWVrX2NhbXAucHJvdG8SBnpwcm90byp3Cg1FSGlk",
            "ZVNlZWtDYW1wEhYKEkVIaWRlU2Vla0NhbXBfTm9uZRAAEhcKEkVIaWRlU2Vl",
            "a0NhbXBfU2VlaxChBhIXChJFSGlkZVNlZWtDYW1wX0hpZGUQogYSHAoXRUhp",
            "ZGVTZWVrQ2FtcF9IaWRlR2hvc3QQowZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EHideSeekCamp), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EHideSeekCamp {
    [pbr::OriginalName("EHideSeekCamp_None")] None = 0,
    [pbr::OriginalName("EHideSeekCamp_Seek")] Seek = 801,
    [pbr::OriginalName("EHideSeekCamp_Hide")] Hide = 802,
    [pbr::OriginalName("EHideSeekCamp_HideGhost")] HideGhost = 803,
  }

  #endregion

}

#endregion Designer generated code
