// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_team_activity_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_team_activity_type.proto</summary>
  public static partial class EnumETeamActivityTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_team_activity_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumETeamActivityTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9lbnVtX2VfdGVhbV9hY3Rpdml0eV90eXBlLnByb3RvEgZ6cHJvdG8qUAoR",
            "RVRlYW1BY3Rpdml0eVR5cGUSHAoYRVRlYW1BY3Rpdml0eVR5cGVEdW5nZW9u",
            "EAASHQoZRVRlYW1BY3Rpdml0eVR5cGVFbnNlbWJsZRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ETeamActivityType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ETeamActivityType {
    [pbr::OriginalName("ETeamActivityTypeDungeon")] Dungeon = 0,
    [pbr::OriginalName("ETeamActivityTypeEnsemble")] Ensemble = 1,
  }

  #endregion

}

#endregion Designer generated code
