// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_edit_blue_print_name_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_edit_blue_print_name_request.proto</summary>
  public static partial class StruEditBluePrintNameRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_edit_blue_print_name_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruEditBluePrintNameRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidzdHJ1X2VkaXRfYmx1ZV9wcmludF9uYW1lX3JlcXVlc3QucHJvdG8SBnpw",
            "cm90bxoaZW51bV9ibHVlX3ByaW50X3R5cGUucHJvdG8icQoYRWRpdEJsdWVQ",
            "cmludE5hbWVSZXF1ZXN0Ei4KD2JsdWVfcHJpbnRfdHlwZRgBIAEoDjIVLnpw",
            "cm90by5CbHVlUHJpbnRUeXBlEgwKBHNsb3QYAiABKAUSFwoPYmx1ZV9wcmlu",
            "dF9uYW1lGAMgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumBluePrintTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.EditBluePrintNameRequest), global::Zproto.EditBluePrintNameRequest.Parser, new[]{ "BluePrintType", "Slot", "BluePrintName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EditBluePrintNameRequest : pb::IMessage<EditBluePrintNameRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EditBluePrintNameRequest> _parser = new pb::MessageParser<EditBluePrintNameRequest>(() => new EditBluePrintNameRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EditBluePrintNameRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruEditBluePrintNameRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EditBluePrintNameRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EditBluePrintNameRequest(EditBluePrintNameRequest other) : this() {
      bluePrintType_ = other.bluePrintType_;
      slot_ = other.slot_;
      bluePrintName_ = other.bluePrintName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EditBluePrintNameRequest Clone() {
      return new EditBluePrintNameRequest(this);
    }

    /// <summary>Field number for the "blue_print_type" field.</summary>
    public const int BluePrintTypeFieldNumber = 1;
    private global::Zproto.BluePrintType bluePrintType_ = global::Zproto.BluePrintType.Outer;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.BluePrintType BluePrintType {
      get { return bluePrintType_; }
      set {
        bluePrintType_ = value;
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private int slot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "blue_print_name" field.</summary>
    public const int BluePrintNameFieldNumber = 3;
    private string bluePrintName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BluePrintName {
      get { return bluePrintName_; }
      set {
        bluePrintName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EditBluePrintNameRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EditBluePrintNameRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BluePrintType != other.BluePrintType) return false;
      if (Slot != other.Slot) return false;
      if (BluePrintName != other.BluePrintName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BluePrintType != global::Zproto.BluePrintType.Outer) hash ^= BluePrintType.GetHashCode();
      if (Slot != 0) hash ^= Slot.GetHashCode();
      if (BluePrintName.Length != 0) hash ^= BluePrintName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BluePrintType != global::Zproto.BluePrintType.Outer) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BluePrintType);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (BluePrintName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BluePrintName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BluePrintType != global::Zproto.BluePrintType.Outer) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BluePrintType);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (BluePrintName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BluePrintName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BluePrintType != global::Zproto.BluePrintType.Outer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BluePrintType);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
      }
      if (BluePrintName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BluePrintName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EditBluePrintNameRequest other) {
      if (other == null) {
        return;
      }
      if (other.BluePrintType != global::Zproto.BluePrintType.Outer) {
        BluePrintType = other.BluePrintType;
      }
      if (other.Slot != 0) {
        Slot = other.Slot;
      }
      if (other.BluePrintName.Length != 0) {
        BluePrintName = other.BluePrintName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BluePrintType = (global::Zproto.BluePrintType) input.ReadEnum();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 26: {
            BluePrintName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BluePrintType = (global::Zproto.BluePrintType) input.ReadEnum();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 26: {
            BluePrintName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
