// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_leader_set_ensemble_params_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_leader_set_ensemble_params_request.proto</summary>
  public static partial class StruLeaderSetEnsembleParamsRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_leader_set_ensemble_params_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruLeaderSetEnsembleParamsRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1zdHJ1X2xlYWRlcl9zZXRfZW5zZW1ibGVfcGFyYW1zX3JlcXVlc3QucHJv",
            "dG8SBnpwcm90bxoiZW51bV9lX2luc3RydW1lbnRfcGxheV9yYW5nZS5wcm90",
            "byJtCh5MZWFkZXJTZXRFbnNlbWJsZVBhcmFtc1JlcXVlc3QSCwoDYnBtGAEg",
            "ASgFEgwKBGJlYXQYAiABKAUSMAoKcGxheV9yYW5nZRgDIAEoDjIcLnpwcm90",
            "by5FSW5zdHJ1bWVudFBsYXlSYW5nZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEInstrumentPlayRangeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.LeaderSetEnsembleParamsRequest), global::Zproto.LeaderSetEnsembleParamsRequest.Parser, new[]{ "Bpm", "Beat", "PlayRange" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LeaderSetEnsembleParamsRequest : pb::IMessage<LeaderSetEnsembleParamsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaderSetEnsembleParamsRequest> _parser = new pb::MessageParser<LeaderSetEnsembleParamsRequest>(() => new LeaderSetEnsembleParamsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaderSetEnsembleParamsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruLeaderSetEnsembleParamsRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderSetEnsembleParamsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderSetEnsembleParamsRequest(LeaderSetEnsembleParamsRequest other) : this() {
      bpm_ = other.bpm_;
      beat_ = other.beat_;
      playRange_ = other.playRange_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderSetEnsembleParamsRequest Clone() {
      return new LeaderSetEnsembleParamsRequest(this);
    }

    /// <summary>Field number for the "bpm" field.</summary>
    public const int BpmFieldNumber = 1;
    private int bpm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Bpm {
      get { return bpm_; }
      set {
        bpm_ = value;
      }
    }

    /// <summary>Field number for the "beat" field.</summary>
    public const int BeatFieldNumber = 2;
    private int beat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Beat {
      get { return beat_; }
      set {
        beat_ = value;
      }
    }

    /// <summary>Field number for the "play_range" field.</summary>
    public const int PlayRangeFieldNumber = 3;
    private global::Zproto.EInstrumentPlayRange playRange_ = global::Zproto.EInstrumentPlayRange.All;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EInstrumentPlayRange PlayRange {
      get { return playRange_; }
      set {
        playRange_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaderSetEnsembleParamsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaderSetEnsembleParamsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Bpm != other.Bpm) return false;
      if (Beat != other.Beat) return false;
      if (PlayRange != other.PlayRange) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Bpm != 0) hash ^= Bpm.GetHashCode();
      if (Beat != 0) hash ^= Beat.GetHashCode();
      if (PlayRange != global::Zproto.EInstrumentPlayRange.All) hash ^= PlayRange.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Bpm != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Bpm);
      }
      if (Beat != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Beat);
      }
      if (PlayRange != global::Zproto.EInstrumentPlayRange.All) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PlayRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Bpm != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Bpm);
      }
      if (Beat != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Beat);
      }
      if (PlayRange != global::Zproto.EInstrumentPlayRange.All) {
        output.WriteRawTag(24);
        output.WriteEnum((int) PlayRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Bpm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Bpm);
      }
      if (Beat != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Beat);
      }
      if (PlayRange != global::Zproto.EInstrumentPlayRange.All) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PlayRange);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaderSetEnsembleParamsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Bpm != 0) {
        Bpm = other.Bpm;
      }
      if (other.Beat != 0) {
        Beat = other.Beat;
      }
      if (other.PlayRange != global::Zproto.EInstrumentPlayRange.All) {
        PlayRange = other.PlayRange;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Bpm = input.ReadInt32();
            break;
          }
          case 16: {
            Beat = input.ReadInt32();
            break;
          }
          case 24: {
            PlayRange = (global::Zproto.EInstrumentPlayRange) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Bpm = input.ReadInt32();
            break;
          }
          case 16: {
            Beat = input.ReadInt32();
            break;
          }
          case 24: {
            PlayRange = (global::Zproto.EInstrumentPlayRange) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
