// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_homeland_update_sub_model_transform_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_homeland_update_sub_model_transform_request.proto</summary>
  public static partial class StruHomelandUpdateSubModelTransformRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_homeland_update_sub_model_transform_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomelandUpdateSubModelTransformRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZzdHJ1X2hvbWVsYW5kX3VwZGF0ZV9zdWJfbW9kZWxfdHJhbnNmb3JtX3Jl",
            "cXVlc3QucHJvdG8SBnpwcm90bxoTc3RydV9pbnRfdmVjMy5wcm90bxoPc3Ry",
            "dV92ZWM0LnByb3RvIr4BCiZIb21lbGFuZFVwZGF0ZVN1Yk1vZGVsVHJhbnNm",
            "b3JtUmVxdWVzdBIWCg5zdHJ1Y3R1cmVfdXVpZBgBIAEoAxIMCgRzbG90GAIg",
            "ASgFEiEKCHBvc2l0aW9uGAMgASgLMg8uenByb3RvLkludFZlYzMSIAoKcXVh",
            "dGVybmlvbhgEIAEoCzIMLnpwcm90by5WZWM0EhAKCGlzX291dGVyGAUgASgI",
            "EhcKD3N1Yl9tb2RlbF9pbmRleBgGIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruIntVec3Reflection.Descriptor, global::Zproto.StruVec4Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomelandUpdateSubModelTransformRequest), global::Zproto.HomelandUpdateSubModelTransformRequest.Parser, new[]{ "StructureUuid", "Slot", "Position", "Quaternion", "IsOuter", "SubModelIndex" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomelandUpdateSubModelTransformRequest : pb::IMessage<HomelandUpdateSubModelTransformRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomelandUpdateSubModelTransformRequest> _parser = new pb::MessageParser<HomelandUpdateSubModelTransformRequest>(() => new HomelandUpdateSubModelTransformRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomelandUpdateSubModelTransformRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomelandUpdateSubModelTransformRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandUpdateSubModelTransformRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandUpdateSubModelTransformRequest(HomelandUpdateSubModelTransformRequest other) : this() {
      structureUuid_ = other.structureUuid_;
      slot_ = other.slot_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      quaternion_ = other.quaternion_ != null ? other.quaternion_.Clone() : null;
      isOuter_ = other.isOuter_;
      subModelIndex_ = other.subModelIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandUpdateSubModelTransformRequest Clone() {
      return new HomelandUpdateSubModelTransformRequest(this);
    }

    /// <summary>Field number for the "structure_uuid" field.</summary>
    public const int StructureUuidFieldNumber = 1;
    private long structureUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StructureUuid {
      get { return structureUuid_; }
      set {
        structureUuid_ = value;
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private int slot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Zproto.IntVec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.IntVec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "quaternion" field.</summary>
    public const int QuaternionFieldNumber = 4;
    private global::Zproto.Vec4 quaternion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.Vec4 Quaternion {
      get { return quaternion_; }
      set {
        quaternion_ = value;
      }
    }

    /// <summary>Field number for the "is_outer" field.</summary>
    public const int IsOuterFieldNumber = 5;
    private bool isOuter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOuter {
      get { return isOuter_; }
      set {
        isOuter_ = value;
      }
    }

    /// <summary>Field number for the "sub_model_index" field.</summary>
    public const int SubModelIndexFieldNumber = 6;
    private int subModelIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SubModelIndex {
      get { return subModelIndex_; }
      set {
        subModelIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomelandUpdateSubModelTransformRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomelandUpdateSubModelTransformRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StructureUuid != other.StructureUuid) return false;
      if (Slot != other.Slot) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Quaternion, other.Quaternion)) return false;
      if (IsOuter != other.IsOuter) return false;
      if (SubModelIndex != other.SubModelIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StructureUuid != 0L) hash ^= StructureUuid.GetHashCode();
      if (Slot != 0) hash ^= Slot.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (quaternion_ != null) hash ^= Quaternion.GetHashCode();
      if (IsOuter != false) hash ^= IsOuter.GetHashCode();
      if (SubModelIndex != 0) hash ^= SubModelIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (quaternion_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Quaternion);
      }
      if (IsOuter != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsOuter);
      }
      if (SubModelIndex != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SubModelIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (quaternion_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Quaternion);
      }
      if (IsOuter != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsOuter);
      }
      if (SubModelIndex != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SubModelIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StructureUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StructureUuid);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (quaternion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quaternion);
      }
      if (IsOuter != false) {
        size += 1 + 1;
      }
      if (SubModelIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SubModelIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomelandUpdateSubModelTransformRequest other) {
      if (other == null) {
        return;
      }
      if (other.StructureUuid != 0L) {
        StructureUuid = other.StructureUuid;
      }
      if (other.Slot != 0) {
        Slot = other.Slot;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Zproto.IntVec3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.quaternion_ != null) {
        if (quaternion_ == null) {
          Quaternion = new global::Zproto.Vec4();
        }
        Quaternion.MergeFrom(other.Quaternion);
      }
      if (other.IsOuter != false) {
        IsOuter = other.IsOuter;
      }
      if (other.SubModelIndex != 0) {
        SubModelIndex = other.SubModelIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Zproto.IntVec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (quaternion_ == null) {
              Quaternion = new global::Zproto.Vec4();
            }
            input.ReadMessage(Quaternion);
            break;
          }
          case 40: {
            IsOuter = input.ReadBool();
            break;
          }
          case 48: {
            SubModelIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Zproto.IntVec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (quaternion_ == null) {
              Quaternion = new global::Zproto.Vec4();
            }
            input.ReadMessage(Quaternion);
            break;
          }
          case 40: {
            IsOuter = input.ReadBool();
            break;
          }
          case 48: {
            SubModelIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
