// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_user_games_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_user_games_info.proto</summary>
  public static partial class StruUserGamesInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_user_games_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruUserGamesInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpzdHJ1X3VzZXJfZ2FtZXNfaW5mby5wcm90bxIGenByb3RvGhRzdHJ1X2dh",
            "bWVfaW5mby5wcm90bxofc3RydV91c2VyX2dhbWVfdGFibGVfaW5mby5wcm90",
            "bxoVc3RydV9kaXJ0eV9tYXNrLnByb3RvIsYBCg1Vc2VyR2FtZXNJbmZvEjgK",
            "CmdhbWVzX2RhdGEYASADKAsyJC56cHJvdG8uVXNlckdhbWVzSW5mby5HYW1l",
            "c0RhdGFFbnRyeRI3ChR1c2VyX2dhbWVfdGFibGVfaW5mbxgCIAEoCzIZLnpw",
            "cm90by5Vc2VyR2FtZVRhYmxlSW5mbxpCCg5HYW1lc0RhdGFFbnRyeRILCgNr",
            "ZXkYASABKAUSHwoFdmFsdWUYAiABKAsyEC56cHJvdG8uR2FtZUluZm86AjgB",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruGameInfoReflection.Descriptor, global::Zproto.StruUserGameTableInfoReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.UserGamesInfo), global::Zproto.UserGamesInfo.Parser, new[]{ "GamesData", "UserGameTableInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UserGamesInfo : pb::IMessage<UserGamesInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserGamesInfo> _parser = new pb::MessageParser<UserGamesInfo>(() => new UserGamesInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserGamesInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruUserGamesInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserGamesInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserGamesInfo(UserGamesInfo other) : this() {
      gamesData_ = other.gamesData_.Clone();
      userGameTableInfo_ = other.userGameTableInfo_ != null ? other.userGameTableInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserGamesInfo Clone() {
      return new UserGamesInfo(this);
    }

    /// <summary>Field number for the "games_data" field.</summary>
    public const int GamesDataFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Zproto.GameInfo>.Codec _map_gamesData_codec
        = new pbc::MapField<int, global::Zproto.GameInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.GameInfo.Parser), 10);
    private readonly pbc::MapField<int, global::Zproto.GameInfo> gamesData_ = new pbc::MapField<int, global::Zproto.GameInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.GameInfo> GamesData {
      get { return gamesData_; }
    }

    /// <summary>Field number for the "user_game_table_info" field.</summary>
    public const int UserGameTableInfoFieldNumber = 2;
    private global::Zproto.UserGameTableInfo userGameTableInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.UserGameTableInfo UserGameTableInfo {
      get { return userGameTableInfo_; }
      set {
        userGameTableInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserGamesInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserGamesInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!GamesData.Equals(other.GamesData)) return false;
      if (!object.Equals(UserGameTableInfo, other.UserGameTableInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= GamesData.GetHashCode();
      if (userGameTableInfo_ != null) hash ^= UserGameTableInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      gamesData_.WriteTo(output, _map_gamesData_codec);
      if (userGameTableInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserGameTableInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      gamesData_.WriteTo(ref output, _map_gamesData_codec);
      if (userGameTableInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserGameTableInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += gamesData_.CalculateSize(_map_gamesData_codec);
      if (userGameTableInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserGameTableInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserGamesInfo other) {
      if (other == null) {
        return;
      }
      gamesData_.MergeFrom(other.gamesData_);
      if (other.userGameTableInfo_ != null) {
        if (userGameTableInfo_ == null) {
          UserGameTableInfo = new global::Zproto.UserGameTableInfo();
        }
        UserGameTableInfo.MergeFrom(other.UserGameTableInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            gamesData_.AddEntriesFrom(input, _map_gamesData_codec);
            break;
          }
          case 18: {
            if (userGameTableInfo_ == null) {
              UserGameTableInfo = new global::Zproto.UserGameTableInfo();
            }
            input.ReadMessage(UserGameTableInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            gamesData_.AddEntriesFrom(ref input, _map_gamesData_codec);
            break;
          }
          case 18: {
            if (userGameTableInfo_ == null) {
              UserGameTableInfo = new global::Zproto.UserGameTableInfo();
            }
            input.ReadMessage(UserGameTableInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
