// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_hide_seek_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_hide_seek_info.proto</summary>
  public static partial class StruHideSeekInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_hide_seek_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHideSeekInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X2hpZGVfc2Vla19pbmZvLnByb3RvEgZ6cHJvdG8aJHN0cnVfaGlk",
            "ZV9zZWVrX3NraWxsX3Nsb3RfaW5mby5wcm90bxoVc3RydV9kaXJ0eV9tYXNr",
            "LnByb3RvIvYDCgxIaWRlU2Vla0luZm8SEQoJd2VhcG9uX2lkGAEgASgFEkYK",
            "EnB1cnN1ZXJfd2VhcG9uX21hcBgCIAMoCzIqLnpwcm90by5IaWRlU2Vla0lu",
            "Zm8uUHVyc3VlcldlYXBvbk1hcEVudHJ5Ek8KF3B1cnN1ZXJfc2tpbGxfc2xv",
            "dF9pbmZvGAMgAygLMi4uenByb3RvLkhpZGVTZWVrSW5mby5QdXJzdWVyU2tp",
            "bGxTbG90SW5mb0VudHJ5EksKFWhpZGVyX3NraWxsX3Nsb3RfaW5mbxgEIAMo",
            "CzIsLnpwcm90by5IaWRlU2Vla0luZm8uSGlkZXJTa2lsbFNsb3RJbmZvRW50",
            "cnkaNwoVUHVyc3VlcldlYXBvbk1hcEVudHJ5EgsKA2tleRgBIAEoBRINCgV2",
            "YWx1ZRgCIAEoCDoCOAEaWgoZUHVyc3VlclNraWxsU2xvdEluZm9FbnRyeRIL",
            "CgNrZXkYASABKAUSLAoFdmFsdWUYAiABKAsyHS56cHJvdG8uSGlkZVNlZWtT",
            "a2lsbFNsb3RJbmZvOgI4ARpYChdIaWRlclNraWxsU2xvdEluZm9FbnRyeRIL",
            "CgNrZXkYASABKAUSLAoFdmFsdWUYAiABKAsyHS56cHJvdG8uSGlkZVNlZWtT",
            "a2lsbFNsb3RJbmZvOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruHideSeekSkillSlotInfoReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HideSeekInfo), global::Zproto.HideSeekInfo.Parser, new[]{ "WeaponId", "PursuerWeaponMap", "PursuerSkillSlotInfo", "HiderSkillSlotInfo" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HideSeekInfo : pb::IMessage<HideSeekInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HideSeekInfo> _parser = new pb::MessageParser<HideSeekInfo>(() => new HideSeekInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HideSeekInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHideSeekInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HideSeekInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HideSeekInfo(HideSeekInfo other) : this() {
      weaponId_ = other.weaponId_;
      pursuerWeaponMap_ = other.pursuerWeaponMap_.Clone();
      pursuerSkillSlotInfo_ = other.pursuerSkillSlotInfo_.Clone();
      hiderSkillSlotInfo_ = other.hiderSkillSlotInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HideSeekInfo Clone() {
      return new HideSeekInfo(this);
    }

    /// <summary>Field number for the "weapon_id" field.</summary>
    public const int WeaponIdFieldNumber = 1;
    private int weaponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WeaponId {
      get { return weaponId_; }
      set {
        weaponId_ = value;
      }
    }

    /// <summary>Field number for the "pursuer_weapon_map" field.</summary>
    public const int PursuerWeaponMapFieldNumber = 2;
    private static readonly pbc::MapField<int, bool>.Codec _map_pursuerWeaponMap_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 18);
    private readonly pbc::MapField<int, bool> pursuerWeaponMap_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> PursuerWeaponMap {
      get { return pursuerWeaponMap_; }
    }

    /// <summary>Field number for the "pursuer_skill_slot_info" field.</summary>
    public const int PursuerSkillSlotInfoFieldNumber = 3;
    private static readonly pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>.Codec _map_pursuerSkillSlotInfo_codec
        = new pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HideSeekSkillSlotInfo.Parser), 26);
    private readonly pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo> pursuerSkillSlotInfo_ = new pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo> PursuerSkillSlotInfo {
      get { return pursuerSkillSlotInfo_; }
    }

    /// <summary>Field number for the "hider_skill_slot_info" field.</summary>
    public const int HiderSkillSlotInfoFieldNumber = 4;
    private static readonly pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>.Codec _map_hiderSkillSlotInfo_codec
        = new pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.HideSeekSkillSlotInfo.Parser), 34);
    private readonly pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo> hiderSkillSlotInfo_ = new pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.HideSeekSkillSlotInfo> HiderSkillSlotInfo {
      get { return hiderSkillSlotInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HideSeekInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HideSeekInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WeaponId != other.WeaponId) return false;
      if (!PursuerWeaponMap.Equals(other.PursuerWeaponMap)) return false;
      if (!PursuerSkillSlotInfo.Equals(other.PursuerSkillSlotInfo)) return false;
      if (!HiderSkillSlotInfo.Equals(other.HiderSkillSlotInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WeaponId != 0) hash ^= WeaponId.GetHashCode();
      hash ^= PursuerWeaponMap.GetHashCode();
      hash ^= PursuerSkillSlotInfo.GetHashCode();
      hash ^= HiderSkillSlotInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WeaponId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WeaponId);
      }
      pursuerWeaponMap_.WriteTo(output, _map_pursuerWeaponMap_codec);
      pursuerSkillSlotInfo_.WriteTo(output, _map_pursuerSkillSlotInfo_codec);
      hiderSkillSlotInfo_.WriteTo(output, _map_hiderSkillSlotInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WeaponId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WeaponId);
      }
      pursuerWeaponMap_.WriteTo(ref output, _map_pursuerWeaponMap_codec);
      pursuerSkillSlotInfo_.WriteTo(ref output, _map_pursuerSkillSlotInfo_codec);
      hiderSkillSlotInfo_.WriteTo(ref output, _map_hiderSkillSlotInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WeaponId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponId);
      }
      size += pursuerWeaponMap_.CalculateSize(_map_pursuerWeaponMap_codec);
      size += pursuerSkillSlotInfo_.CalculateSize(_map_pursuerSkillSlotInfo_codec);
      size += hiderSkillSlotInfo_.CalculateSize(_map_hiderSkillSlotInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HideSeekInfo other) {
      if (other == null) {
        return;
      }
      if (other.WeaponId != 0) {
        WeaponId = other.WeaponId;
      }
      pursuerWeaponMap_.MergeFrom(other.pursuerWeaponMap_);
      pursuerSkillSlotInfo_.MergeFrom(other.pursuerSkillSlotInfo_);
      hiderSkillSlotInfo_.MergeFrom(other.hiderSkillSlotInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 18: {
            pursuerWeaponMap_.AddEntriesFrom(input, _map_pursuerWeaponMap_codec);
            break;
          }
          case 26: {
            pursuerSkillSlotInfo_.AddEntriesFrom(input, _map_pursuerSkillSlotInfo_codec);
            break;
          }
          case 34: {
            hiderSkillSlotInfo_.AddEntriesFrom(input, _map_hiderSkillSlotInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 18: {
            pursuerWeaponMap_.AddEntriesFrom(ref input, _map_pursuerWeaponMap_codec);
            break;
          }
          case 26: {
            pursuerSkillSlotInfo_.AddEntriesFrom(ref input, _map_pursuerSkillSlotInfo_codec);
            break;
          }
          case 34: {
            hiderSkillSlotInfo_.AddEntriesFrom(ref input, _map_hiderSkillSlotInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
