// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_game_table_key.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_game_table_key.proto</summary>
  public static partial class StruGameTableKeyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_game_table_key.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruGameTableKeyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlzdHJ1X2dhbWVfdGFibGVfa2V5LnByb3RvEgZ6cHJvdG8aFXN0cnVfZGly",
            "dHlfbWFzay5wcm90byLHAQoMR2FtZVRhYmxlS2V5EhcKD2dhbWVfdGFibGVf",
            "Z3VpZBgBIAEoCRIXCg9nYW1lX3RhYmxlX3V1aWQYAiABKAMSHQoVZ2FtZV90",
            "YWJsZV9zY2VuZV9ndWlkGAMgASgJEiEKGWdhbWVfdGFibGVfc3ViX3NjZW5l",
            "X3V1aWQYBCABKAMSDwoHZ2FtZV9pZBgFIAEoBRITCgtzb3VyY2VfdHlwZRgG",
            "IAEoBRIdChVnYW1lX3RhYmxlX3JvdW5kX2d1aWQYByABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.GameTableKey), global::Zproto.GameTableKey.Parser, new[]{ "GameTableGuid", "GameTableUuid", "GameTableSceneGuid", "GameTableSubSceneUuid", "GameId", "SourceType", "GameTableRoundGuid" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameTableKey : pb::IMessage<GameTableKey>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameTableKey> _parser = new pb::MessageParser<GameTableKey>(() => new GameTableKey());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameTableKey> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruGameTableKeyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameTableKey() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameTableKey(GameTableKey other) : this() {
      gameTableGuid_ = other.gameTableGuid_;
      gameTableUuid_ = other.gameTableUuid_;
      gameTableSceneGuid_ = other.gameTableSceneGuid_;
      gameTableSubSceneUuid_ = other.gameTableSubSceneUuid_;
      gameId_ = other.gameId_;
      sourceType_ = other.sourceType_;
      gameTableRoundGuid_ = other.gameTableRoundGuid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameTableKey Clone() {
      return new GameTableKey(this);
    }

    /// <summary>Field number for the "game_table_guid" field.</summary>
    public const int GameTableGuidFieldNumber = 1;
    private string gameTableGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameTableGuid {
      get { return gameTableGuid_; }
      set {
        gameTableGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "game_table_uuid" field.</summary>
    public const int GameTableUuidFieldNumber = 2;
    private long gameTableUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long GameTableUuid {
      get { return gameTableUuid_; }
      set {
        gameTableUuid_ = value;
      }
    }

    /// <summary>Field number for the "game_table_scene_guid" field.</summary>
    public const int GameTableSceneGuidFieldNumber = 3;
    private string gameTableSceneGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameTableSceneGuid {
      get { return gameTableSceneGuid_; }
      set {
        gameTableSceneGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "game_table_sub_scene_uuid" field.</summary>
    public const int GameTableSubSceneUuidFieldNumber = 4;
    private long gameTableSubSceneUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long GameTableSubSceneUuid {
      get { return gameTableSubSceneUuid_; }
      set {
        gameTableSubSceneUuid_ = value;
      }
    }

    /// <summary>Field number for the "game_id" field.</summary>
    public const int GameIdFieldNumber = 5;
    private int gameId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameId {
      get { return gameId_; }
      set {
        gameId_ = value;
      }
    }

    /// <summary>Field number for the "source_type" field.</summary>
    public const int SourceTypeFieldNumber = 6;
    private int sourceType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SourceType {
      get { return sourceType_; }
      set {
        sourceType_ = value;
      }
    }

    /// <summary>Field number for the "game_table_round_guid" field.</summary>
    public const int GameTableRoundGuidFieldNumber = 7;
    private string gameTableRoundGuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameTableRoundGuid {
      get { return gameTableRoundGuid_; }
      set {
        gameTableRoundGuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameTableKey);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameTableKey other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameTableGuid != other.GameTableGuid) return false;
      if (GameTableUuid != other.GameTableUuid) return false;
      if (GameTableSceneGuid != other.GameTableSceneGuid) return false;
      if (GameTableSubSceneUuid != other.GameTableSubSceneUuid) return false;
      if (GameId != other.GameId) return false;
      if (SourceType != other.SourceType) return false;
      if (GameTableRoundGuid != other.GameTableRoundGuid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameTableGuid.Length != 0) hash ^= GameTableGuid.GetHashCode();
      if (GameTableUuid != 0L) hash ^= GameTableUuid.GetHashCode();
      if (GameTableSceneGuid.Length != 0) hash ^= GameTableSceneGuid.GetHashCode();
      if (GameTableSubSceneUuid != 0L) hash ^= GameTableSubSceneUuid.GetHashCode();
      if (GameId != 0) hash ^= GameId.GetHashCode();
      if (SourceType != 0) hash ^= SourceType.GetHashCode();
      if (GameTableRoundGuid.Length != 0) hash ^= GameTableRoundGuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameTableGuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameTableGuid);
      }
      if (GameTableUuid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(GameTableUuid);
      }
      if (GameTableSceneGuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GameTableSceneGuid);
      }
      if (GameTableSubSceneUuid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(GameTableSubSceneUuid);
      }
      if (GameId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(GameId);
      }
      if (SourceType != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SourceType);
      }
      if (GameTableRoundGuid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(GameTableRoundGuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameTableGuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(GameTableGuid);
      }
      if (GameTableUuid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(GameTableUuid);
      }
      if (GameTableSceneGuid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(GameTableSceneGuid);
      }
      if (GameTableSubSceneUuid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(GameTableSubSceneUuid);
      }
      if (GameId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(GameId);
      }
      if (SourceType != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SourceType);
      }
      if (GameTableRoundGuid.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(GameTableRoundGuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameTableGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameTableGuid);
      }
      if (GameTableUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameTableUuid);
      }
      if (GameTableSceneGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameTableSceneGuid);
      }
      if (GameTableSubSceneUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GameTableSubSceneUuid);
      }
      if (GameId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameId);
      }
      if (SourceType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceType);
      }
      if (GameTableRoundGuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameTableRoundGuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameTableKey other) {
      if (other == null) {
        return;
      }
      if (other.GameTableGuid.Length != 0) {
        GameTableGuid = other.GameTableGuid;
      }
      if (other.GameTableUuid != 0L) {
        GameTableUuid = other.GameTableUuid;
      }
      if (other.GameTableSceneGuid.Length != 0) {
        GameTableSceneGuid = other.GameTableSceneGuid;
      }
      if (other.GameTableSubSceneUuid != 0L) {
        GameTableSubSceneUuid = other.GameTableSubSceneUuid;
      }
      if (other.GameId != 0) {
        GameId = other.GameId;
      }
      if (other.SourceType != 0) {
        SourceType = other.SourceType;
      }
      if (other.GameTableRoundGuid.Length != 0) {
        GameTableRoundGuid = other.GameTableRoundGuid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            GameTableGuid = input.ReadString();
            break;
          }
          case 16: {
            GameTableUuid = input.ReadInt64();
            break;
          }
          case 26: {
            GameTableSceneGuid = input.ReadString();
            break;
          }
          case 32: {
            GameTableSubSceneUuid = input.ReadInt64();
            break;
          }
          case 40: {
            GameId = input.ReadInt32();
            break;
          }
          case 48: {
            SourceType = input.ReadInt32();
            break;
          }
          case 58: {
            GameTableRoundGuid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            GameTableGuid = input.ReadString();
            break;
          }
          case 16: {
            GameTableUuid = input.ReadInt64();
            break;
          }
          case 26: {
            GameTableSceneGuid = input.ReadString();
            break;
          }
          case 32: {
            GameTableSubSceneUuid = input.ReadInt64();
            break;
          }
          case 40: {
            GameId = input.ReadInt32();
            break;
          }
          case 48: {
            SourceType = input.ReadInt32();
            break;
          }
          case 58: {
            GameTableRoundGuid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
