// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_homeland_hang_fashion_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_homeland_hang_fashion_request.proto</summary>
  public static partial class StruHomelandHangFashionRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_homeland_hang_fashion_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomelandHangFashionRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihzdHJ1X2hvbWVsYW5kX2hhbmdfZmFzaGlvbl9yZXF1ZXN0LnByb3RvEgZ6",
            "cHJvdG8aIHN0cnVfaG9tZWxhbmRfc2xvdF9mYXNoaW9uLnByb3RvInkKGkhv",
            "bWVsYW5kSGFuZ0Zhc2hpb25SZXF1ZXN0EhYKDnN0cnVjdHVyZV91dWlkGAEg",
            "ASgDEhAKCGlzX291dGVyGAIgASgIEjEKDGZhc2hpb25fZGF0YRgDIAMoCzIb",
            "Lnpwcm90by5Ib21lbGFuZFNsb3RGYXNoaW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruHomelandSlotFashionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomelandHangFashionRequest), global::Zproto.HomelandHangFashionRequest.Parser, new[]{ "StructureUuid", "IsOuter", "FashionData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomelandHangFashionRequest : pb::IMessage<HomelandHangFashionRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomelandHangFashionRequest> _parser = new pb::MessageParser<HomelandHangFashionRequest>(() => new HomelandHangFashionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomelandHangFashionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomelandHangFashionRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandHangFashionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandHangFashionRequest(HomelandHangFashionRequest other) : this() {
      structureUuid_ = other.structureUuid_;
      isOuter_ = other.isOuter_;
      fashionData_ = other.fashionData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandHangFashionRequest Clone() {
      return new HomelandHangFashionRequest(this);
    }

    /// <summary>Field number for the "structure_uuid" field.</summary>
    public const int StructureUuidFieldNumber = 1;
    private long structureUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StructureUuid {
      get { return structureUuid_; }
      set {
        structureUuid_ = value;
      }
    }

    /// <summary>Field number for the "is_outer" field.</summary>
    public const int IsOuterFieldNumber = 2;
    private bool isOuter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOuter {
      get { return isOuter_; }
      set {
        isOuter_ = value;
      }
    }

    /// <summary>Field number for the "fashion_data" field.</summary>
    public const int FashionDataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Zproto.HomelandSlotFashion> _repeated_fashionData_codec
        = pb::FieldCodec.ForMessage(26, global::Zproto.HomelandSlotFashion.Parser);
    private readonly pbc::RepeatedField<global::Zproto.HomelandSlotFashion> fashionData_ = new pbc::RepeatedField<global::Zproto.HomelandSlotFashion>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.HomelandSlotFashion> FashionData {
      get { return fashionData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomelandHangFashionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomelandHangFashionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StructureUuid != other.StructureUuid) return false;
      if (IsOuter != other.IsOuter) return false;
      if(!fashionData_.Equals(other.fashionData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StructureUuid != 0L) hash ^= StructureUuid.GetHashCode();
      if (IsOuter != false) hash ^= IsOuter.GetHashCode();
      hash ^= fashionData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (IsOuter != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsOuter);
      }
      fashionData_.WriteTo(output, _repeated_fashionData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (IsOuter != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsOuter);
      }
      fashionData_.WriteTo(ref output, _repeated_fashionData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StructureUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StructureUuid);
      }
      if (IsOuter != false) {
        size += 1 + 1;
      }
      size += fashionData_.CalculateSize(_repeated_fashionData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomelandHangFashionRequest other) {
      if (other == null) {
        return;
      }
      if (other.StructureUuid != 0L) {
        StructureUuid = other.StructureUuid;
      }
      if (other.IsOuter != false) {
        IsOuter = other.IsOuter;
      }
      fashionData_.Add(other.fashionData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            IsOuter = input.ReadBool();
            break;
          }
          case 26: {
            fashionData_.AddEntriesFrom(input, _repeated_fashionData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            IsOuter = input.ReadBool();
            break;
          }
          case 26: {
            fashionData_.AddEntriesFrom(ref input, _repeated_fashionData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
