// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_dungeon_phase_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_dungeon_phase_data.proto</summary>
  public static partial class StruDungeonPhaseDataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_dungeon_phase_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruDungeonPhaseDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zdHJ1X2R1bmdlb25fcGhhc2VfZGF0YS5wcm90bxIGenByb3RvGh5lbnVt",
            "X2VfZHVuZ2Vvbl9wbGF5X3R5cGUucHJvdG8aFXN0cnVfZGlydHlfbWFzay5w",
            "cm90byKGAQoQRHVuZ2VvblBoYXNlRGF0YRImCgR0eXBlGAEgASgOMhguenBy",
            "b3RvLkVEdW5nZW9uUGxheVR5cGUSEAoIcGhhc2VfaWQYAiABKAUSEgoKYmVn",
            "aW5fdGltZRgDIAEoAxISCgpwaGFzZV90aW1lGAQgASgDEhAKCGVuZF90aW1l",
            "GAUgASgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEDungeonPlayTypeReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.DungeonPhaseData), global::Zproto.DungeonPhaseData.Parser, new[]{ "Type", "PhaseId", "BeginTime", "PhaseTime", "EndTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DungeonPhaseData : pb::IMessage<DungeonPhaseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DungeonPhaseData> _parser = new pb::MessageParser<DungeonPhaseData>(() => new DungeonPhaseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DungeonPhaseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruDungeonPhaseDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonPhaseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonPhaseData(DungeonPhaseData other) : this() {
      type_ = other.type_;
      phaseId_ = other.phaseId_;
      beginTime_ = other.beginTime_;
      phaseTime_ = other.phaseTime_;
      endTime_ = other.endTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonPhaseData Clone() {
      return new DungeonPhaseData(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Zproto.EDungeonPlayType type_ = global::Zproto.EDungeonPlayType.DungeonPlayTypeNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EDungeonPlayType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "phase_id" field.</summary>
    public const int PhaseIdFieldNumber = 2;
    private int phaseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PhaseId {
      get { return phaseId_; }
      set {
        phaseId_ = value;
      }
    }

    /// <summary>Field number for the "begin_time" field.</summary>
    public const int BeginTimeFieldNumber = 3;
    private long beginTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BeginTime {
      get { return beginTime_; }
      set {
        beginTime_ = value;
      }
    }

    /// <summary>Field number for the "phase_time" field.</summary>
    public const int PhaseTimeFieldNumber = 4;
    private long phaseTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PhaseTime {
      get { return phaseTime_; }
      set {
        phaseTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 5;
    private long endTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DungeonPhaseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DungeonPhaseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (PhaseId != other.PhaseId) return false;
      if (BeginTime != other.BeginTime) return false;
      if (PhaseTime != other.PhaseTime) return false;
      if (EndTime != other.EndTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Zproto.EDungeonPlayType.DungeonPlayTypeNull) hash ^= Type.GetHashCode();
      if (PhaseId != 0) hash ^= PhaseId.GetHashCode();
      if (BeginTime != 0L) hash ^= BeginTime.GetHashCode();
      if (PhaseTime != 0L) hash ^= PhaseTime.GetHashCode();
      if (EndTime != 0L) hash ^= EndTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Zproto.EDungeonPlayType.DungeonPlayTypeNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (PhaseId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PhaseId);
      }
      if (BeginTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BeginTime);
      }
      if (PhaseTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PhaseTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(EndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Zproto.EDungeonPlayType.DungeonPlayTypeNull) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (PhaseId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PhaseId);
      }
      if (BeginTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BeginTime);
      }
      if (PhaseTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PhaseTime);
      }
      if (EndTime != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(EndTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Zproto.EDungeonPlayType.DungeonPlayTypeNull) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (PhaseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PhaseId);
      }
      if (BeginTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BeginTime);
      }
      if (PhaseTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PhaseTime);
      }
      if (EndTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DungeonPhaseData other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Zproto.EDungeonPlayType.DungeonPlayTypeNull) {
        Type = other.Type;
      }
      if (other.PhaseId != 0) {
        PhaseId = other.PhaseId;
      }
      if (other.BeginTime != 0L) {
        BeginTime = other.BeginTime;
      }
      if (other.PhaseTime != 0L) {
        PhaseTime = other.PhaseTime;
      }
      if (other.EndTime != 0L) {
        EndTime = other.EndTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Zproto.EDungeonPlayType) input.ReadEnum();
            break;
          }
          case 16: {
            PhaseId = input.ReadInt32();
            break;
          }
          case 24: {
            BeginTime = input.ReadInt64();
            break;
          }
          case 32: {
            PhaseTime = input.ReadInt64();
            break;
          }
          case 40: {
            EndTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Zproto.EDungeonPlayType) input.ReadEnum();
            break;
          }
          case 16: {
            PhaseId = input.ReadInt32();
            break;
          }
          case 24: {
            BeginTime = input.ReadInt64();
            break;
          }
          case 32: {
            PhaseTime = input.ReadInt64();
            break;
          }
          case 40: {
            EndTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
