// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_homeland_retrieve_sub_model_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_homeland_retrieve_sub_model_request.proto</summary>
  public static partial class StruHomelandRetrieveSubModelRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_homeland_retrieve_sub_model_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruHomelandRetrieveSubModelRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5zdHJ1X2hvbWVsYW5kX3JldHJpZXZlX3N1Yl9tb2RlbF9yZXF1ZXN0LnBy",
            "b3RvEgZ6cHJvdG8icgofSG9tZWxhbmRSZXRyaWV2ZVN1Yk1vZGVsUmVxdWVz",
            "dBIWCg5zdHJ1Y3R1cmVfdXVpZBgBIAEoAxIMCgRzbG90GAIgASgFEhcKD3N1",
            "Yl9tb2RlbF9pbmRleBgDIAEoBRIQCghpc19vdXRlchgEIAEoCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.HomelandRetrieveSubModelRequest), global::Zproto.HomelandRetrieveSubModelRequest.Parser, new[]{ "StructureUuid", "Slot", "SubModelIndex", "IsOuter" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HomelandRetrieveSubModelRequest : pb::IMessage<HomelandRetrieveSubModelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HomelandRetrieveSubModelRequest> _parser = new pb::MessageParser<HomelandRetrieveSubModelRequest>(() => new HomelandRetrieveSubModelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HomelandRetrieveSubModelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruHomelandRetrieveSubModelRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandRetrieveSubModelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandRetrieveSubModelRequest(HomelandRetrieveSubModelRequest other) : this() {
      structureUuid_ = other.structureUuid_;
      slot_ = other.slot_;
      subModelIndex_ = other.subModelIndex_;
      isOuter_ = other.isOuter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HomelandRetrieveSubModelRequest Clone() {
      return new HomelandRetrieveSubModelRequest(this);
    }

    /// <summary>Field number for the "structure_uuid" field.</summary>
    public const int StructureUuidFieldNumber = 1;
    private long structureUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StructureUuid {
      get { return structureUuid_; }
      set {
        structureUuid_ = value;
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private int slot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "sub_model_index" field.</summary>
    public const int SubModelIndexFieldNumber = 3;
    private int subModelIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SubModelIndex {
      get { return subModelIndex_; }
      set {
        subModelIndex_ = value;
      }
    }

    /// <summary>Field number for the "is_outer" field.</summary>
    public const int IsOuterFieldNumber = 4;
    private bool isOuter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOuter {
      get { return isOuter_; }
      set {
        isOuter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HomelandRetrieveSubModelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HomelandRetrieveSubModelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StructureUuid != other.StructureUuid) return false;
      if (Slot != other.Slot) return false;
      if (SubModelIndex != other.SubModelIndex) return false;
      if (IsOuter != other.IsOuter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StructureUuid != 0L) hash ^= StructureUuid.GetHashCode();
      if (Slot != 0) hash ^= Slot.GetHashCode();
      if (SubModelIndex != 0) hash ^= SubModelIndex.GetHashCode();
      if (IsOuter != false) hash ^= IsOuter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (SubModelIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SubModelIndex);
      }
      if (IsOuter != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsOuter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StructureUuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StructureUuid);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Slot);
      }
      if (SubModelIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SubModelIndex);
      }
      if (IsOuter != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsOuter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StructureUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StructureUuid);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
      }
      if (SubModelIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SubModelIndex);
      }
      if (IsOuter != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HomelandRetrieveSubModelRequest other) {
      if (other == null) {
        return;
      }
      if (other.StructureUuid != 0L) {
        StructureUuid = other.StructureUuid;
      }
      if (other.Slot != 0) {
        Slot = other.Slot;
      }
      if (other.SubModelIndex != 0) {
        SubModelIndex = other.SubModelIndex;
      }
      if (other.IsOuter != false) {
        IsOuter = other.IsOuter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 24: {
            SubModelIndex = input.ReadInt32();
            break;
          }
          case 32: {
            IsOuter = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StructureUuid = input.ReadInt64();
            break;
          }
          case 16: {
            Slot = input.ReadInt32();
            break;
          }
          case 24: {
            SubModelIndex = input.ReadInt32();
            break;
          }
          case 32: {
            IsOuter = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
