// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_structure.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_structure.proto</summary>
  public static partial class StruStructureReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_structure.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruStructureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzdHJ1X3N0cnVjdHVyZS5wcm90bxIGenByb3RvGhpzdHJ1X2dhbWVfdGFi",
            "bGVfZGF0YS5wcm90bxoTc3RydV9pbnRfdmVjMy5wcm90bxoic3RydV9zdHJ1",
            "Y3R1cmVfZmFybWxhbmRfaW5mby5wcm90bxohc3RydV9zdHJ1Y3R1cmVfZmFz",
            "aGlvbl9kYXRhLnByb3RvGiNzdHJ1X3N0cnVjdHVyZV9sYW1wbGlnaHRfaW5m",
            "by5wcm90bxoic3RydV9zdHJ1Y3R1cmVfbWF0ZXJpYWxfaW5mby5wcm90bxoj",
            "c3RydV9zdHJ1Y3R1cmVfc3ViX21vZGVsX2RhdGEucHJvdG8aD3N0cnVfdmVj",
            "NC5wcm90byKOBAoJU3RydWN0dXJlEgwKBHV1aWQYASABKAMSEwoLY2xpZW50",
            "X3V1aWQYAiABKAMSEAoIZ3JvdXBfaWQYAyABKAMSDwoHaXRlbV9pZBgEIAEo",
            "BRIPCgdjaGFyX2lkGAUgASgDEiEKCHBvc2l0aW9uGAYgASgLMg8uenByb3Rv",
            "LkludFZlYzMSIAoKcXVhdGVybmlvbhgHIAEoCzIMLnpwcm90by5WZWM0EhgK",
            "EG9wZXJhdG9yX2NoYXJfaWQYCCABKAMSDAoEbmFtZRgJIAEoCRI0Cg1tYXRl",
            "cmlhbF9pbmZvGAogASgLMh0uenByb3RvLlN0cnVjdHVyZU1hdGVyaWFsSW5m",
            "bxI2Cg5sYW1wbGlnaHRfaW5mbxgLIAEoCzIeLnpwcm90by5TdHJ1Y3R1cmVM",
            "YW1wbGlnaHRJbmZvEjQKDWZhcm1sYW5kX2luZm8YDCABKAsyHS56cHJvdG8u",
            "U3RydWN0dXJlRmFybWxhbmRJbmZvEjIKDGZhc2hpb25fZGF0YRgNIAEoCzIc",
            "Lnpwcm90by5TdHJ1Y3R1cmVGYXNoaW9uRGF0YRI1Cg5zdWJfbW9kZWxfZGF0",
            "YRgOIAEoCzIdLnpwcm90by5TdHJ1Y3R1cmVTdWJNb2RlbERhdGESLgoPZ2Ft",
            "ZV90YWJsZV9kYXRhGA8gASgLMhUuenByb3RvLkdhbWVUYWJsZURhdGFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruGameTableDataReflection.Descriptor, global::Zproto.StruIntVec3Reflection.Descriptor, global::Zproto.StruStructureFarmlandInfoReflection.Descriptor, global::Zproto.StruStructureFashionDataReflection.Descriptor, global::Zproto.StruStructureLamplightInfoReflection.Descriptor, global::Zproto.StruStructureMaterialInfoReflection.Descriptor, global::Zproto.StruStructureSubModelDataReflection.Descriptor, global::Zproto.StruVec4Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.Structure), global::Zproto.Structure.Parser, new[]{ "Uuid", "ClientUuid", "GroupId", "ItemId", "CharId", "Position", "Quaternion", "OperatorCharId", "Name", "MaterialInfo", "LamplightInfo", "FarmlandInfo", "FashionData", "SubModelData", "GameTableData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Structure : pb::IMessage<Structure>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Structure> _parser = new pb::MessageParser<Structure>(() => new Structure());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Structure> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruStructureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Structure() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Structure(Structure other) : this() {
      uuid_ = other.uuid_;
      clientUuid_ = other.clientUuid_;
      groupId_ = other.groupId_;
      itemId_ = other.itemId_;
      charId_ = other.charId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      quaternion_ = other.quaternion_ != null ? other.quaternion_.Clone() : null;
      operatorCharId_ = other.operatorCharId_;
      name_ = other.name_;
      materialInfo_ = other.materialInfo_ != null ? other.materialInfo_.Clone() : null;
      lamplightInfo_ = other.lamplightInfo_ != null ? other.lamplightInfo_.Clone() : null;
      farmlandInfo_ = other.farmlandInfo_ != null ? other.farmlandInfo_.Clone() : null;
      fashionData_ = other.fashionData_ != null ? other.fashionData_.Clone() : null;
      subModelData_ = other.subModelData_ != null ? other.subModelData_.Clone() : null;
      gameTableData_ = other.gameTableData_ != null ? other.gameTableData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Structure Clone() {
      return new Structure(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private long uuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uuid {
      get { return uuid_; }
      set {
        uuid_ = value;
      }
    }

    /// <summary>Field number for the "client_uuid" field.</summary>
    public const int ClientUuidFieldNumber = 2;
    private long clientUuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientUuid {
      get { return clientUuid_; }
      set {
        clientUuid_ = value;
      }
    }

    /// <summary>Field number for the "group_id" field.</summary>
    public const int GroupIdFieldNumber = 3;
    private long groupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long GroupId {
      get { return groupId_; }
      set {
        groupId_ = value;
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 4;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "char_id" field.</summary>
    public const int CharIdFieldNumber = 5;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 6;
    private global::Zproto.IntVec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.IntVec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "quaternion" field.</summary>
    public const int QuaternionFieldNumber = 7;
    private global::Zproto.Vec4 quaternion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.Vec4 Quaternion {
      get { return quaternion_; }
      set {
        quaternion_ = value;
      }
    }

    /// <summary>Field number for the "operator_char_id" field.</summary>
    public const int OperatorCharIdFieldNumber = 8;
    private long operatorCharId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OperatorCharId {
      get { return operatorCharId_; }
      set {
        operatorCharId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 9;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "material_info" field.</summary>
    public const int MaterialInfoFieldNumber = 10;
    private global::Zproto.StructureMaterialInfo materialInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.StructureMaterialInfo MaterialInfo {
      get { return materialInfo_; }
      set {
        materialInfo_ = value;
      }
    }

    /// <summary>Field number for the "lamplight_info" field.</summary>
    public const int LamplightInfoFieldNumber = 11;
    private global::Zproto.StructureLamplightInfo lamplightInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.StructureLamplightInfo LamplightInfo {
      get { return lamplightInfo_; }
      set {
        lamplightInfo_ = value;
      }
    }

    /// <summary>Field number for the "farmland_info" field.</summary>
    public const int FarmlandInfoFieldNumber = 12;
    private global::Zproto.StructureFarmlandInfo farmlandInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.StructureFarmlandInfo FarmlandInfo {
      get { return farmlandInfo_; }
      set {
        farmlandInfo_ = value;
      }
    }

    /// <summary>Field number for the "fashion_data" field.</summary>
    public const int FashionDataFieldNumber = 13;
    private global::Zproto.StructureFashionData fashionData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.StructureFashionData FashionData {
      get { return fashionData_; }
      set {
        fashionData_ = value;
      }
    }

    /// <summary>Field number for the "sub_model_data" field.</summary>
    public const int SubModelDataFieldNumber = 14;
    private global::Zproto.StructureSubModelData subModelData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.StructureSubModelData SubModelData {
      get { return subModelData_; }
      set {
        subModelData_ = value;
      }
    }

    /// <summary>Field number for the "game_table_data" field.</summary>
    public const int GameTableDataFieldNumber = 15;
    private global::Zproto.GameTableData gameTableData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.GameTableData GameTableData {
      get { return gameTableData_; }
      set {
        gameTableData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Structure);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Structure other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (ClientUuid != other.ClientUuid) return false;
      if (GroupId != other.GroupId) return false;
      if (ItemId != other.ItemId) return false;
      if (CharId != other.CharId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Quaternion, other.Quaternion)) return false;
      if (OperatorCharId != other.OperatorCharId) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(MaterialInfo, other.MaterialInfo)) return false;
      if (!object.Equals(LamplightInfo, other.LamplightInfo)) return false;
      if (!object.Equals(FarmlandInfo, other.FarmlandInfo)) return false;
      if (!object.Equals(FashionData, other.FashionData)) return false;
      if (!object.Equals(SubModelData, other.SubModelData)) return false;
      if (!object.Equals(GameTableData, other.GameTableData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uuid != 0L) hash ^= Uuid.GetHashCode();
      if (ClientUuid != 0L) hash ^= ClientUuid.GetHashCode();
      if (GroupId != 0L) hash ^= GroupId.GetHashCode();
      if (ItemId != 0) hash ^= ItemId.GetHashCode();
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (quaternion_ != null) hash ^= Quaternion.GetHashCode();
      if (OperatorCharId != 0L) hash ^= OperatorCharId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (materialInfo_ != null) hash ^= MaterialInfo.GetHashCode();
      if (lamplightInfo_ != null) hash ^= LamplightInfo.GetHashCode();
      if (farmlandInfo_ != null) hash ^= FarmlandInfo.GetHashCode();
      if (fashionData_ != null) hash ^= FashionData.GetHashCode();
      if (subModelData_ != null) hash ^= SubModelData.GetHashCode();
      if (gameTableData_ != null) hash ^= GameTableData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uuid);
      }
      if (ClientUuid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ClientUuid);
      }
      if (GroupId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(GroupId);
      }
      if (ItemId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ItemId);
      }
      if (CharId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(CharId);
      }
      if (position_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Position);
      }
      if (quaternion_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Quaternion);
      }
      if (OperatorCharId != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(OperatorCharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (materialInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MaterialInfo);
      }
      if (lamplightInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(LamplightInfo);
      }
      if (farmlandInfo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(FarmlandInfo);
      }
      if (fashionData_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(FashionData);
      }
      if (subModelData_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(SubModelData);
      }
      if (gameTableData_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(GameTableData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uuid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uuid);
      }
      if (ClientUuid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ClientUuid);
      }
      if (GroupId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(GroupId);
      }
      if (ItemId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ItemId);
      }
      if (CharId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(CharId);
      }
      if (position_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Position);
      }
      if (quaternion_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Quaternion);
      }
      if (OperatorCharId != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(OperatorCharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (materialInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MaterialInfo);
      }
      if (lamplightInfo_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(LamplightInfo);
      }
      if (farmlandInfo_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(FarmlandInfo);
      }
      if (fashionData_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(FashionData);
      }
      if (subModelData_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(SubModelData);
      }
      if (gameTableData_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(GameTableData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uuid);
      }
      if (ClientUuid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientUuid);
      }
      if (GroupId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(GroupId);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (quaternion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quaternion);
      }
      if (OperatorCharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OperatorCharId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (materialInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MaterialInfo);
      }
      if (lamplightInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LamplightInfo);
      }
      if (farmlandInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FarmlandInfo);
      }
      if (fashionData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FashionData);
      }
      if (subModelData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubModelData);
      }
      if (gameTableData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameTableData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Structure other) {
      if (other == null) {
        return;
      }
      if (other.Uuid != 0L) {
        Uuid = other.Uuid;
      }
      if (other.ClientUuid != 0L) {
        ClientUuid = other.ClientUuid;
      }
      if (other.GroupId != 0L) {
        GroupId = other.GroupId;
      }
      if (other.ItemId != 0) {
        ItemId = other.ItemId;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Zproto.IntVec3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.quaternion_ != null) {
        if (quaternion_ == null) {
          Quaternion = new global::Zproto.Vec4();
        }
        Quaternion.MergeFrom(other.Quaternion);
      }
      if (other.OperatorCharId != 0L) {
        OperatorCharId = other.OperatorCharId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.materialInfo_ != null) {
        if (materialInfo_ == null) {
          MaterialInfo = new global::Zproto.StructureMaterialInfo();
        }
        MaterialInfo.MergeFrom(other.MaterialInfo);
      }
      if (other.lamplightInfo_ != null) {
        if (lamplightInfo_ == null) {
          LamplightInfo = new global::Zproto.StructureLamplightInfo();
        }
        LamplightInfo.MergeFrom(other.LamplightInfo);
      }
      if (other.farmlandInfo_ != null) {
        if (farmlandInfo_ == null) {
          FarmlandInfo = new global::Zproto.StructureFarmlandInfo();
        }
        FarmlandInfo.MergeFrom(other.FarmlandInfo);
      }
      if (other.fashionData_ != null) {
        if (fashionData_ == null) {
          FashionData = new global::Zproto.StructureFashionData();
        }
        FashionData.MergeFrom(other.FashionData);
      }
      if (other.subModelData_ != null) {
        if (subModelData_ == null) {
          SubModelData = new global::Zproto.StructureSubModelData();
        }
        SubModelData.MergeFrom(other.SubModelData);
      }
      if (other.gameTableData_ != null) {
        if (gameTableData_ == null) {
          GameTableData = new global::Zproto.GameTableData();
        }
        GameTableData.MergeFrom(other.GameTableData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uuid = input.ReadInt64();
            break;
          }
          case 16: {
            ClientUuid = input.ReadInt64();
            break;
          }
          case 24: {
            GroupId = input.ReadInt64();
            break;
          }
          case 32: {
            ItemId = input.ReadInt32();
            break;
          }
          case 40: {
            CharId = input.ReadInt64();
            break;
          }
          case 50: {
            if (position_ == null) {
              Position = new global::Zproto.IntVec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 58: {
            if (quaternion_ == null) {
              Quaternion = new global::Zproto.Vec4();
            }
            input.ReadMessage(Quaternion);
            break;
          }
          case 64: {
            OperatorCharId = input.ReadInt64();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 82: {
            if (materialInfo_ == null) {
              MaterialInfo = new global::Zproto.StructureMaterialInfo();
            }
            input.ReadMessage(MaterialInfo);
            break;
          }
          case 90: {
            if (lamplightInfo_ == null) {
              LamplightInfo = new global::Zproto.StructureLamplightInfo();
            }
            input.ReadMessage(LamplightInfo);
            break;
          }
          case 98: {
            if (farmlandInfo_ == null) {
              FarmlandInfo = new global::Zproto.StructureFarmlandInfo();
            }
            input.ReadMessage(FarmlandInfo);
            break;
          }
          case 106: {
            if (fashionData_ == null) {
              FashionData = new global::Zproto.StructureFashionData();
            }
            input.ReadMessage(FashionData);
            break;
          }
          case 114: {
            if (subModelData_ == null) {
              SubModelData = new global::Zproto.StructureSubModelData();
            }
            input.ReadMessage(SubModelData);
            break;
          }
          case 122: {
            if (gameTableData_ == null) {
              GameTableData = new global::Zproto.GameTableData();
            }
            input.ReadMessage(GameTableData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uuid = input.ReadInt64();
            break;
          }
          case 16: {
            ClientUuid = input.ReadInt64();
            break;
          }
          case 24: {
            GroupId = input.ReadInt64();
            break;
          }
          case 32: {
            ItemId = input.ReadInt32();
            break;
          }
          case 40: {
            CharId = input.ReadInt64();
            break;
          }
          case 50: {
            if (position_ == null) {
              Position = new global::Zproto.IntVec3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 58: {
            if (quaternion_ == null) {
              Quaternion = new global::Zproto.Vec4();
            }
            input.ReadMessage(Quaternion);
            break;
          }
          case 64: {
            OperatorCharId = input.ReadInt64();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
          case 82: {
            if (materialInfo_ == null) {
              MaterialInfo = new global::Zproto.StructureMaterialInfo();
            }
            input.ReadMessage(MaterialInfo);
            break;
          }
          case 90: {
            if (lamplightInfo_ == null) {
              LamplightInfo = new global::Zproto.StructureLamplightInfo();
            }
            input.ReadMessage(LamplightInfo);
            break;
          }
          case 98: {
            if (farmlandInfo_ == null) {
              FarmlandInfo = new global::Zproto.StructureFarmlandInfo();
            }
            input.ReadMessage(FarmlandInfo);
            break;
          }
          case 106: {
            if (fashionData_ == null) {
              FashionData = new global::Zproto.StructureFashionData();
            }
            input.ReadMessage(FashionData);
            break;
          }
          case 114: {
            if (subModelData_ == null) {
              SubModelData = new global::Zproto.StructureSubModelData();
            }
            input.ReadMessage(SubModelData);
            break;
          }
          case 122: {
            if (gameTableData_ == null) {
              GameTableData = new global::Zproto.GameTableData();
            }
            input.ReadMessage(GameTableData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
