// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_ichiban_kuji_one_draw_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_ichiban_kuji_one_draw_info.proto</summary>
  public static partial class StruIchibanKujiOneDrawInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_ichiban_kuji_one_draw_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruIchibanKujiOneDrawInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVzdHJ1X2ljaGliYW5fa3VqaV9vbmVfZHJhd19pbmZvLnByb3RvEgZ6cHJv",
            "dG8aD3N0cnVfaXRlbS5wcm90byJ2ChZJY2hpYmFuS3VqaU9uZURyYXdJbmZv",
            "EhoKBGl0ZW0YASABKAsyDC56cHJvdG8uSXRlbRIUCgxsdWNrX3Bvb2xfaWQY",
            "AiABKAUSFAoMcHJpemVfcmV0dXJuGAMgASgFEhQKDHByaXplX2tleV9pZBgE",
            "IAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.IchibanKujiOneDrawInfo), global::Zproto.IchibanKujiOneDrawInfo.Parser, new[]{ "Item", "LuckPoolId", "PrizeReturn", "PrizeKeyId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IchibanKujiOneDrawInfo : pb::IMessage<IchibanKujiOneDrawInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IchibanKujiOneDrawInfo> _parser = new pb::MessageParser<IchibanKujiOneDrawInfo>(() => new IchibanKujiOneDrawInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IchibanKujiOneDrawInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruIchibanKujiOneDrawInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibanKujiOneDrawInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibanKujiOneDrawInfo(IchibanKujiOneDrawInfo other) : this() {
      item_ = other.item_ != null ? other.item_.Clone() : null;
      luckPoolId_ = other.luckPoolId_;
      prizeReturn_ = other.prizeReturn_;
      prizeKeyId_ = other.prizeKeyId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IchibanKujiOneDrawInfo Clone() {
      return new IchibanKujiOneDrawInfo(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::Zproto.Item item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.Item Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "luck_pool_id" field.</summary>
    public const int LuckPoolIdFieldNumber = 2;
    private int luckPoolId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LuckPoolId {
      get { return luckPoolId_; }
      set {
        luckPoolId_ = value;
      }
    }

    /// <summary>Field number for the "prize_return" field.</summary>
    public const int PrizeReturnFieldNumber = 3;
    private int prizeReturn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PrizeReturn {
      get { return prizeReturn_; }
      set {
        prizeReturn_ = value;
      }
    }

    /// <summary>Field number for the "prize_key_id" field.</summary>
    public const int PrizeKeyIdFieldNumber = 4;
    private int prizeKeyId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PrizeKeyId {
      get { return prizeKeyId_; }
      set {
        prizeKeyId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IchibanKujiOneDrawInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IchibanKujiOneDrawInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      if (LuckPoolId != other.LuckPoolId) return false;
      if (PrizeReturn != other.PrizeReturn) return false;
      if (PrizeKeyId != other.PrizeKeyId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      if (LuckPoolId != 0) hash ^= LuckPoolId.GetHashCode();
      if (PrizeReturn != 0) hash ^= PrizeReturn.GetHashCode();
      if (PrizeKeyId != 0) hash ^= PrizeKeyId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (LuckPoolId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LuckPoolId);
      }
      if (PrizeReturn != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PrizeReturn);
      }
      if (PrizeKeyId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PrizeKeyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (LuckPoolId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LuckPoolId);
      }
      if (PrizeReturn != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PrizeReturn);
      }
      if (PrizeKeyId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PrizeKeyId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (LuckPoolId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LuckPoolId);
      }
      if (PrizeReturn != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PrizeReturn);
      }
      if (PrizeKeyId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PrizeKeyId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IchibanKujiOneDrawInfo other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::Zproto.Item();
        }
        Item.MergeFrom(other.Item);
      }
      if (other.LuckPoolId != 0) {
        LuckPoolId = other.LuckPoolId;
      }
      if (other.PrizeReturn != 0) {
        PrizeReturn = other.PrizeReturn;
      }
      if (other.PrizeKeyId != 0) {
        PrizeKeyId = other.PrizeKeyId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::Zproto.Item();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            LuckPoolId = input.ReadInt32();
            break;
          }
          case 24: {
            PrizeReturn = input.ReadInt32();
            break;
          }
          case 32: {
            PrizeKeyId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::Zproto.Item();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            LuckPoolId = input.ReadInt32();
            break;
          }
          case 24: {
            PrizeReturn = input.ReadInt32();
            break;
          }
          case 32: {
            PrizeKeyId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
